### ISSUE TITLE
Publishing checklist

### ISSUE THREAD

**Issue by LikeTheSalad** [elastic/apm-agent-android#11]
- [x] Use single Byte buddy version across all the subprojects.
- [x] Use release variant as maven publish module of the android-sdk subproject.
- [x] Check otel desugaring.
- [x] Check App Bundle files instrumentation.
- [x] Android assets generation compatible with all 7.2+ AGP versions
- [x] Make source headers generate on assembling
- [x] Update loggers default name
- [x] Update android logger level debug config
- [x] Running android-test from terminal
- [x] Adding tests for api breaking changes
- [x] Setting span type to "mobile"
- [x] Adding process.runtime attrs to resources
- [x] Adding okhttp spans tests
- [x] Adding "postDeploy" task
