### ISSUE TITLE
Manual instrumentation of opbeans-android

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-android#2]
This a first step towards an end-to-end POC of instrumenting an Android application.
Use the [OpenTelemetry API and SDK](https://github.com/open-telemetry/opentelemetry-java) to enrich the opbeans-android App with instrumentation code.

The goal is to see end-to-end tracing data in Kibana from view loads / user interactions in the app through http requests into the backend and correlation with the backend traces.

## Tasks
- [x] create a separate git branch on opbeans-android
- [x] setup OTel SDK within opbeans-android
- [x] instrument views
- [x] instrument http requests
- [x] validate tracing data in Kibana
