### ISSUE TITLE
Add documentation to the Elastic doc build

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-android#28]
This issue explains the steps required to publish documentation to the Elastic documentation build powered by [elastic/docs](github.com/elastic/docs). Let me know when you're ready and I can get started on these tasks.

### Phase one

Create basic docs. These docs will disconnected from the doc build for this phase. Docs should (mostly) follow the _slightly outdated_ [Agent documentation template](https://github.com/elastic/apm-dev/issues/425). Here's a recent example: https://github.com/elastic/apm-agent-php/pull/48.

- [x] https://github.com/elastic/apm-agent-android/issues/25

### Phase two

We have content! Now we can add `elastic/apm-agent-android` to Elastic's doc build and publish.

- [x] Open a PR in `elastic/docs` to add to the build
- [x] Open infra ticket to add the `elasticsearch/ci docs` check to this repo
- [x] Add the `elasticsearch/ci docs` webhook to the repo
- [x] Update `elastic/apm-contrib` https://github.com/elastic/apm-contrib/pull/61
- [x] Update `elastic/apm` https://github.com/elastic/apm/pull/721
- [x] Update `elastic/apm-dev` https://github.com/elastic/apm-dev/pull/898
- [x] Add page header https://github.com/elastic/apm-agent-android/pull/52
- [x] Remove any remaining documentation content from readme and link to published docs

### Phase three

Hook the Android Reference into the rest of the Stack documentation. No list as docs change frequently, but inspiration can be taken from https://github.com/elastic/observability-docs/issues/383 and https://github.com/elastic/observability-docs/issues/792.

- [ ] Link from stack documentation to the Android Reference.

**Comment by LikeTheSalad** [comment]
Hi @bmorelli25 - I've just created this PR to generate the initial content for the phase one: https://github.com/elastic/apm-agent-android/pull/46

**Comment by LikeTheSalad** [comment]
Hi @bmorelli25, continuing with the set of steps, I've just created these tickets:

- On elastic/docs: https://github.com/elastic/docs/issues/2564
- On infra: https://github.com/elastic/ci/issues/984 (it's not the old `infra` repo so I'm not sure if that's the right place)

Just wanted to keep track of those here, and also I wanted to check with you if I opened them in the right places and if there's something in the descriptions that might be missing 😬

Cheers!

**Comment by bmorelli25** [comment]
Yup, that's fine. I'll open both of those PRs!

**Comment by LikeTheSalad** [comment]
I think this can be closed now, many thanks @bmorelli25 🚀
