### ISSUE TITLE
[META] Auto-instrumentation (compile time)

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-android#3]
Onboarding the Android APM Agent should be as easy as possible. While runtime bytecode instrumentation (BCI) is not possible on Android, we can leverage compile time BCI using [Android Buddy](https://github.com/LikeTheSalad/android-buddy).

## Steps

- [x] Initialize Android APM Agent as an Android Buddy-based Gradle plugin
- [x] Provide instrumentation plugins for popular (with Android) HTTP clients
- [x] Collect Resource Attributes
- [x] Make instrumentation and BCI work with both Java-based and Kotlin-based Android apps.
- [x] Provide instrumentation plugins for Views and their lifecycle
