### ISSUE TITLE
[META] Continuous Testing with different devices and OS versions

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-android#4]
## Phase 1:

- [x] Write a test script that can be executed in SauceLabs -https://github.com/elastic/apm-agent-android/issues/10
  - [x] on a simulator
  - [x] on the device farm
- [x]  Automate test execution to make it run periodically (e.g. once every X minutes, X to be defined)
  - [x] add saucelabs credentials to vault
  - [x] automated script that pulls edge + saucelabs creds from vault to automate saucelabs run.
  - [x] add build process that uploads app file to saucelabs for testing

## Phase 2:
- [ ] Parameterize test scripts OR randomize test execution, i.e. run test on/with different  ...
  - [x] ... device models
  - [x] ... OS versions
  - [ ] ... geo locations
  - [ ] ... opbeans-android app versions
