### ISSUE TITLE
OSS Checklist

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-android#5]
# Product Checklist

This checklist should be used by existing and newly-acquired products to ensure compliance with Elastic's open-source policy.

- [ ] Product build produces a list of dependencies included both in source code and in the product distribution
- [ ] Manual investigation has ensured that all dependencies are represented in the list
- [ ] Each dependency reviewed and either in the [Green List](https://github.com/elastic/open-source/blob/main/elastic-product-policy.md#green-list) or has an [exception](https://github.com/elastic/open-source/blob/main/elastic-product-policy.md#exception-list) (Note that the [Yellow List](https://github.com/elastic/open-source/blob/main/elastic-product-policy.md#yellow-list) contains a few automatic exceptions)
- [ ] Product repositories contain [required notices](https://github.com/elastic/open-source/blob/main/elastic-product-policy.md#notices-required-in-each-repository)
- [ ] Product source code files all have [appropriate license headers](https://github.com/elastic/open-source/blob/main/elastic-product-policy.md#code-written-or-contributed-directly-to-an-elastic-project)
- [ ] Third-party code contained in product repositories (including vendored code and copy/pasted code) is appropriately marked and [exports](https://github.com/elastic/open-source/blob/main/elastic-product-policy.md#third-party-code-in-an-elastic-repository-eg-copy-paste-vendoring-etc) `NOTICE.txt` and license information like other dependencies
- [ ] Product distribution contains `NOTICE.txt` file consists of the following items concatenated together:
    - Contents of product's `NOTICE.txt` file
    - For each dependency, contents of dependency's `NOTICE.txt` (if existing)
    - For each dependency, the full and exact license text copied from dependency's distribution/repository
- [ ] Manual investigation has ensured that the build system does not use any components with licenses on the Red list

## For products not using release manager

- [ ] - Each build creates a file describing all dependencies

## Optional but encouraged

- [ ] - The product build does not permit adding a dependency without automatic export in the list
